# Use container-based infrastructure
sudo: false
dist: xenial

language: scala
jdk:
  - openjdk10
scala:
  - 2.12.8
  - 2.13.0

stages:
  - name: test
  - name: coverage
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: test
      env: TEST="compile"
      script: sbt ++$TRAVIS_SCALA_VERSION clean compile test
    - stage: coverage
      env: TEST="coverage"
      script: sbt ++$TRAVIS_SCALA_VERSION coverage coverageReport
    - stage: release
      script: sbt ci-release

# These directories are cached to a cloud storage provider "close" to the infrastructure the builds run on.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - git fetch --tags