# Use container-based infrastructure
sudo: false
dist: xenial

language: scala
jdk:
  - openjdk10
scala:
  - 2.12.8


# These directories are cached to a cloud storage provider "close" to the infrastructure the builds run on.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)